# -*- coding: utf-8 -*-
"""Problem 1: LRU Cache.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aptPG7BTv6gXZ7rLxMLPTPYhA7O3w3a2
"""

from collections import OrderedDict 
class LRU_Cache(object):

    def __init__(self, capacity):
        # Initialize class variables
        self.cache = OrderedDict()
        self.capacity  = capacity

    def get(self, key):
        # Retrieve item from provided key. Return -1 if nonexistent. 
        if key in self.cache:
          self.cache.move_to_end(key)
          return self.cache[key]
        return -1

    def set(self, key, value):
        if key<0:
          print('Key can not be null')
          return
        # Set the value if the key is not present in the cache. If the cache is at capacity remove the oldest item.
        self.cache[key] = value
        self.cache.move_to_end(key)
        if len(self.cache)>self.capacity:
          self.cache.popitem(last=False)
        #print(self.cache)

# Test1
our_cache = LRU_Cache(5)

our_cache.set(1, 1)
our_cache.set(2, 2)
our_cache.set(3, 3)
our_cache.set(4, 4)
 

print('pass' if our_cache.get(1) == 1 else 'fail')       
# expected output: 1
print('pass' if our_cache.get(2)==2 else 'fail')    
# expected output: 2
print('pass' if our_cache.get(9)==-1 else 'fail')        
# expected output: -1 


our_cache.set(5, 5) 
our_cache.set(6, 6)


print('pass' if our_cache.get(3)==-1 else 'fail')    
# expected output: -1 
print('pass' if our_cache.get(6)==6 else 'fail')    
# expected output: 6
print('pass' if our_cache.get(1)==1 else 'fail')    
# expected output: 1

print('\n-----------------------------------\n')

#Test 2
our_cache = LRU_Cache(3)
our_cache.set(0, 0)
our_cache.set(1, 1)
our_cache.set(2, 2)

our_cache.set(1, 10)
our_cache.set(0, 5)
our_cache.set(2, 17)

print('pass' if our_cache.get(0)==5 else 'fail')
# expected output: 5
print('pass' if our_cache.get(1)== 10 else 'fail')
# expected output: 10
print('pass' if our_cache.get(2)==17 else 'fail')
# expected output: 17

print('\n-----------------------------------\n')

#Test 3
our_cache = LRU_Cache(0)
our_cache.set(1, 1)
# expected output: "Can't perform operations on 0 capacity cache"
print('pass' if our_cache.get(17)==-1 else 'fail')
# expected output: -1

